const CHARACTER_IMAGES: Record<string, any> = {
  agumon:         require('../assets/images/characters/agumon.gif'),
  agumonSaver:    require('../assets/images/characters/agumon_saver.gif'),
  geoGreymon:     require('../assets/images/characters/geoGreymon.gif'),
  rizeGreymon:    require('../assets/images/characters/rizeGreymon.gif'),
  shineGreymon:   require('../assets/images/characters/shineGreymon.gif'),
  gabumon:        require('../assets/images/characters/gabumon.gif'),
  demiDevimon:    require('../assets/images/characters/demiDevimon.gif'),
  devimon:        require('../assets/images/characters/devimon.gif'),
  myotismon:      require('../assets/images/characters/myotismon.gif'),
  vnonMyotismon:  require('../assets/images/characters/vnonMyotismon.gif'),
  greymon:        require('../assets/images/characters/greymon.gif'),
  metalGreymon:   require('../assets/images/characters/metalGreymon.gif'),
  warGreymon:     require('../assets/images/characters/warGreymon.gif'),
  garurumon:      require('../assets/images/characters/garurumon.gif'),
  wereGarurumon:  require('../assets/images/characters/wereGarurumon.gif'),
  metalGarurumon: require('../assets/images/characters/metalGarurumon.gif'),
  gulusGammamon:  require('../assets/images/characters/gulusGammamon.gif'),
  omegamon:       require('../assets/images/characters/omegamon.gif'),
  guilmon:        require('../assets/images/characters/guilmon.webp'),
  growlmon:       require('../assets/images/characters/growlmon.webp'),
  megaloGrowlmon: require('../assets/images/characters/megaloGrowlmon.webp'),
  gallantmon:              require('../assets/images/characters/gallantmon.webp'),
  gallantmonCrimsonMode:   require('../assets/images/characters/gallantmonCrimsonMode.webp'),
  seraphimon:              require('../assets/images/characters/seraphimon.gif'),
};

export default CHARACTER_IMAGES;
